config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  get 'properties', to: 'pages#index', as: :properties

  get 'favorites', to: 'users#favorites'

  resources :houses, only: %i[show] do
    member do
      post 'add_favorite', to: 'houses#add_favorite'
      post 'remove_favorite', to: 'houses#remove_favorite'
    end
  end

  resources :apartments, only: %i[show] do
    member do
      post 'add_favorite', to: 'apartments#add_favorite'
      post 'remove_favorite', to: 'apartments#remove_favorite'
    end
  end

  resources :cities, only: %i[] do
    member do
      post 'add_recent_location', to: 'cities#add_recent_location'
    end
  end

  resources :boroughs, only: %i[] do
    member do
      post 'add_recent_location', to: 'boroughs#add_recent_location'
    end
  end

  resources :researches, only: %i[create index]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :researches, dependent: :destroy

  has_many :favorite_apartments, dependent: :destroy
  has_many :apartments, through: :favorite_apartments

  has_many :favorite_houses, dependent: :destroy
  has_many :houses, through: :favorite_houses
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def favorites
    @apartments = current_user.apartments
    @houses = current_user.houses

    @favorites = @apartments + @houses

    @apartments_markers = add_markers(@apartments)
    @houses_markers = add_markers(@houses)

    @markers = @apartments_markers + @houses_markers
  end

  private

  def add_markers(properties)
    properties.geocoded.map do |property|
      {
        lat: property.latitude,
        lng: property.longitude,
        partial: render_to_string(partial: "marker", locals: { property: property }),
        id: property.id,
        info_window: render_to_string(partial: "info_window", locals: { favorites: @favorites, property: property })
      }
    end
  end
end

app/views/users/_favorite_action.html.erb
<% if favorites.present? && favorites.include?(property) %>

  <div data-action="click->favorite#removeFavorite"
      data-property-id="<%= property.id %>"
      data-type="<%= property.class.name.downcase %>s">
    <div class="favorite-heart">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="heart-icon active">
        <path d="M11.645 20.91l-.007-.003-.022-.012a15.247 15.247 0 01-.383-.218 25.18 25.18 0 01-4.244-3.17C4.688 15.36 2.25 12.174 2.25 8.25 2.25 5.322 4.714 3 7.688 3A5.5 5.5 0 0112 5.052 5.5 5.5 0 0116.313 3c2.973 0 5.437 2.322 5.437 5.25 0 3.925-2.438 7.111-4.739 9.256a25.175 25.175 0 01-4.244 3.17 15.247 15.247 0 01-.383.219l-.022.012-.007.004-.003.001a.752.752 0 01-.704 0l-.003-.001z" />
      </svg>
    </div>
  </div>

<% else %>

  <div data-action="click->favorite#addFavorite"
      data-property-id="<%= property.id %>"
      data-type="<%= property.class.name.downcase %>s">
    <div class="favorite-heart">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="heart-icon">
        <path d="M11.645 20.91l-.007-.003-.022-.012a15.247 15.247 0 01-.383-.218 25.18 25.18 0 01-4.244-3.17C4.688 15.36 2.25 12.174 2.25 8.25 2.25 5.322 4.714 3 7.688 3A5.5 5.5 0 0112 5.052 5.5 5.5 0 0116.313 3c2.973 0 5.437 2.322 5.437 5.25 0 3.925-2.438 7.111-4.739 9.256a25.175 25.175 0 01-4.244 3.17 15.247 15.247 0 01-.383.219l-.022.012-.007.004-.003.001a.752.752 0 01-.704 0l-.003-.001z" />
      </svg>
    </div>
  </div>

<% end %>

app/views/users/_info_window.html.erb
<%= render "favorite_action", favorites: @favorites, property: property %>

<%= image_tag property.image_url, class: "image", alt: "photo de l'appartement" %>
<div class="content">
  <p class="address"><%= property.address %></p>
  <p class="title">
    <%= render "shared/property_title", property: property %>
  </p>
  <p class="price"><%= property.price %> €</p>
</div>

app/views/users/_marker.html.erb
<div class="marker" id="marker<%= property.id %>" data-map-target="marker">
  <p class="price"><%= property.price %> €</p>
</div>

app/views/users/favorites.html.erb
<div class="favorite-container"
     data-controller="map"
     data-map-markers-value="<%= @markers.to_json %>"
     data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  <div class="favorite-cards">
    <div class="actions">
      <%= link_to :back, class: "action-back" do %>
        <i class="fa-solid fa-arrow-left back-icon"></i>
      <% end %>

      <h3 class="title">Mes favoris</h3>

    </div>
    <% @favorites.each do |property| %>
      <div class="favorite-link-action"
           data-action="mouseover->map#showMarker mouseout->map#hideMarker"
           data-marker-id="<%= property.id %>">

        <%= link_to property.instance_of?(Apartment) ? apartment_path(property) : house_path(property), class:"favorite-card" do %>

          <div class="favorite-image">
            <%= image_tag property.image_url, class:"image" %>
          </div>

          <div class="favorite-content">

            <div class="main-content">
              <p class="favorite-location">
                <%= property.borough.name if property.borough %>
                <%= property.city.name %>
              </p>

              <h4 class="favorite-title">
                <%= render "shared/property_title", property: property %>
              </h4>

              <div class="line"></div>

              <p class="favorite-infos">
                <%= pluralize(property.rooms, "pièce") %>
                <%= pluralize(property.bedrooms, "chambre") %>
            </div>

            <div class="infos">
              <h3 class="price bold"><%= property.price %> €</h3>
            </div>

          </div>

        <% end %>

        <%= render "favorite_action", favorites: @favorites, property: property %>
      </div>

    <% end %>
  </div>
  <div class="map"
       data-map-target="map">
  </div>
</div>