config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  get 'properties', to: 'pages#index', as: :properties

  get 'favorites', to: 'users#favorites'

  resources :houses, only: %i[show] do
    member do
      post 'add_favorite', to: 'houses#add_favorite'
      post 'remove_favorite', to: 'houses#remove_favorite'
    end
  end

  resources :apartments, only: %i[show] do
    member do
      post 'add_favorite', to: 'apartments#add_favorite'
      post 'remove_favorite', to: 'apartments#remove_favorite'
    end
  end

  resources :cities, only: %i[] do
    member do
      post 'add_recent_location', to: 'cities#add_recent_location'
    end
  end

  resources :boroughs, only: %i[] do
    member do
      post 'add_recent_location', to: 'boroughs#add_recent_location'
    end
  end

  resources :researches, only: %i[create index]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert success" data-controller="notice" data-favorite-target="notification">
    <%= notice.html_safe %>
    <i class="fa-solid fa-xmark" data-action="click->notice#close" ></i>
  </div>
<% end %>
<% if alert %>
  <div class="alert error" data-controller="notice" data-favorite-target="notification">
    <%= alert.html_safe %>
    <i class="fa-solid fa-xmark" data-action="click->notice#close" ></i>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="nav">



  <%= link_to root_path, class: "logo" do %>
    <span class="logo-letter extrabold">N</span>
    <span class="logo-letter bold">A</span>
    <span class="logo-letter semibold">P</span>
    <span class="logo-letter medium">O</span>
    <span class="logo-letter regular">L</span>
    <span class="logo-letter light">É</span>
    <span class="logo-letter extralight">O</span>
    <span class="logo-letter thin">N</span>
  <% end %>

  <div class="menu-btn" data-action="click->nav#displayMenu">

    <p class="menu-text">MENU</p>

    <div class="menu-hamburger">
      <span class="line top-line"></span>
      <span class="line middle-line"></span>
      <span class="line bottom-line"></span>
    </div>

  </div>

</nav>

<div class="menu" data-nav-target="menu" data-action="mouseover->nav#dontHideMenu">
  <% if user_signed_in? %>
    <%= link_to "Déconnexion", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Connexion", new_user_session_path %>
  <% end %>
  <%= link_to "fav", favorites_path %>
</div>

app/views/shared/_property_title.html.erb
<%= translate_type(property.class.name) %>
<%= "#{translate_status(property.status)} de" if property.status %>
<%= property.surface %>m2
<%= humanize_project(property.project) %>